const KEY='zerostress-trips-v1';
const LANG_KEY='zerostress-language';
const icons=['✈️','🌴','🏖️','🏔️','🏙️','🚗','🏝️','❤️','👨‍👩‍👧‍👦','👯','🎒','♨️','🍷','🎉','🌍'];
const colors=['#4f7cff','#22a699','#f59e0b','#ef6a6a','#9b6cff','#ec4899','#14b8a6','#64748b'];
const i18n={
 es:{my_trips:'MIS VIAJES',travel_is_yours:'Tu viaje. Tu historia.',home_intro:'Crea viajes con tu propio color, imagen y personalidad.',new_trip:'Nuevo viaje',empty_title:'Todavía no tienes viajes',empty_text:'Crea el primero y dale su propia identidad.',create_first:'Crear mi primer viaje',create_trip:'Crear viaje',trip_name:'Nombre del viaje',destination:'Destino',start_date:'Fecha de inicio',end_date:'Fecha de fin',travelers:'Viajeros',trip_phrase:'Frase del viaje',identity:'Identidad del viaje',icon:'Icono',color:'Color',upload_image:'Subir imagen',save_trip:'Guardar viaje',overview:'Inicio',itinerary:'Itinerario',reservations:'Reservas',expenses:'Gastos',moments:'Momentos',edit:'Editar',delete:'Eliminar',days:'días',no_dates:'Sin fechas',no_destination:'Sin destino',add_day:'Añadir día',coming_soon:'Esta sección la construiremos en la siguiente fase.',trip_saved:'Viaje guardado.'},
 en:{my_trips:'MY TRIPS',travel_is_yours:'Your trip. Your story.',home_intro:'Create trips with your own color, image and personality.',new_trip:'New trip',empty_title:'You have no trips yet',empty_text:'Create your first one and give it its own identity.',create_first:'Create my first trip',create_trip:'Create trip',trip_name:'Trip name',destination:'Destination',start_date:'Start date',end_date:'End date',travelers:'Travelers',trip_phrase:'Trip phrase',identity:'Trip identity',icon:'Icon',color:'Color',upload_image:'Upload image',save_trip:'Save trip',overview:'Home',itinerary:'Itinerary',reservations:'Bookings',expenses:'Expenses',moments:'Moments',edit:'Edit',delete:'Delete',days:'days',no_dates:'No dates',no_destination:'No destination',add_day:'Add day',coming_soon:'We will build this section in the next phase.',trip_saved:'Trip saved.'},
 fr:{my_trips:'MES VOYAGES',travel_is_yours:'Votre voyage. Votre histoire.',home_intro:'Créez des voyages avec votre couleur, votre image et votre personnalité.',new_trip:'Nouveau voyage',empty_title:"Vous n'avez pas encore de voyages",empty_text:'Créez le premier et donnez-lui sa propre identité.',create_first:'Créer mon premier voyage',create_trip:'Créer un voyage',trip_name:'Nom du voyage',destination:'Destination',start_date:'Date de début',end_date:'Date de fin',travelers:'Voyageurs',trip_phrase:'Phrase du voyage',identity:'Identité du voyage',icon:'Icône',color:'Couleur',upload_image:'Importer une image',save_trip:'Enregistrer',overview:'Accueil',itinerary:'Itinéraire',reservations:'Réservations',expenses:'Dépenses',moments:'Moments',edit:'Modifier',delete:'Supprimer',days:'jours',no_dates:'Sans dates',no_destination:'Sans destination',add_day:'Ajouter un jour',coming_soon:'Cette section sera construite lors de la prochaine phase.',trip_saved:'Voyage enregistré.'},
 de:{my_trips:'MEINE REISEN',travel_is_yours:'Deine Reise. Deine Geschichte.',home_intro:'Erstelle Reisen mit deiner eigenen Farbe, deinem Bild und deiner Persönlichkeit.',new_trip:'Neue Reise',empty_title:'Noch keine Reisen',empty_text:'Erstelle deine erste Reise und gib ihr eine eigene Identität.',create_first:'Erste Reise erstellen',create_trip:'Reise erstellen',trip_name:'Name der Reise',destination:'Reiseziel',start_date:'Startdatum',end_date:'Enddatum',travelers:'Reisende',trip_phrase:'Reisespruch',identity:'Reise-Identität',icon:'Symbol',color:'Farbe',upload_image:'Bild hochladen',save_trip:'Reise speichern',overview:'Start',itinerary:'Reiseplan',reservations:'Buchungen',expenses:'Ausgaben',moments:'Momente',edit:'Bearbeiten',delete:'Löschen',days:'Tage',no_dates:'Keine Daten',no_destination:'Kein Reiseziel',add_day:'Tag hinzufügen',coming_soon:'Diesen Bereich bauen wir in der nächsten Phase.',trip_saved:'Reise gespeichert.'},
 it:{my_trips:'I MIEI VIAGGI',travel_is_yours:'Il tuo viaggio. La tua storia.',home_intro:'Crea viaggi con il tuo colore, la tua immagine e la tua personalità.',new_trip:'Nuovo viaggio',empty_title:'Non hai ancora viaggi',empty_text:'Crea il primo e dagli una propria identità.',create_first:'Crea il mio primo viaggio',create_trip:'Crea viaggio',trip_name:'Nome del viaggio',destination:'Destinazione',start_date:'Data di inizio',end_date:'Data di fine',travelers:'Viaggiatori',trip_phrase:'Frase del viaggio',identity:'Identità del viaggio',icon:'Icona',color:'Colore',upload_image:'Carica immagine',save_trip:'Salva viaggio',overview:'Home',itinerary:'Itinerario',reservations:'Prenotazioni',expenses:'Spese',moments:'Momenti',edit:'Modifica',delete:'Elimina',days:'giorni',no_dates:'Senza date',no_destination:'Nessuna destinazione',add_day:'Aggiungi giorno',coming_soon:'Questa sezione sarà costruita nella prossima fase.',trip_saved:'Viaggio salvato.'}
};
let lang=localStorage.getItem(LANG_KEY)||'es', trips=load(), currentId=null, editingId=null, selectedIcon=icons[0], selectedColor=colors[0], selectedImage='';
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return []}}
function save(){localStorage.setItem(KEY,JSON.stringify(trips))}
function t(k){return i18n[lang]?.[k]||i18n.es[k]||k}
function applyLang(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));document.getElementById('languageLabel').textContent=lang.toUpperCase();renderHome();if(currentId)renderTrip(currentId)}
function formatDate(s){if(!s)return '';const d=new Date(s+'T12:00:00');return new Intl.DateTimeFormat(lang,{day:'numeric',month:'short',year:'numeric'}).format(d)}
function daysBetween(a,b){if(!a||!b)return null;return Math.max(1,Math.round((new Date(b)-new Date(a))/86400000)+1)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderHome(){const grid=document.getElementById('tripsGrid'), empty=document.getElementById('emptyState');grid.innerHTML='';empty.classList.toggle('hidden',trips.length>0);trips.forEach(trip=>{const card=document.createElement('article');card.className='trip-card';card.style.setProperty('--trip-color',trip.color);const media=trip.image?`<img src="${trip.image}" alt="">`:`<div class="trip-symbol">${trip.icon}</div>`;const date=trip.start&&trip.end?`${formatDate(trip.start)} → ${formatDate(trip.end)}`:t('no_dates');card.innerHTML=`<button class="card-main" aria-label="${esc(trip.name)}">${media}<div class="trip-card-overlay"><div class="trip-destination">${esc(trip.destination||t('no_destination'))}</div><h2>${esc(trip.name)}</h2><div class="trip-meta">${date}</div><div class="traveler-line">${esc(trip.travelers||'')}</div></div></button><div class="card-actions"><button data-action="edit">✏️ ${t('edit')}</button><button data-action="delete">🗑️ ${t('delete')}</button></div>`;card.querySelector('.card-main').onclick=()=>openTrip(trip.id);card.querySelector('[data-action=edit]').onclick=()=>openModal(trip.id);card.querySelector('[data-action=delete]').onclick=()=>removeTrip(trip.id);grid.appendChild(card)})}
function setupPickers(){const ip=document.getElementById('iconPicker'),cp=document.getElementById('colorPicker');ip.innerHTML=icons.map(x=>`<button type="button" class="pick icon-pick ${x===selectedIcon?'selected':''}" data-v="${x}">${x}</button>`).join('');cp.innerHTML=colors.map(x=>`<button type="button" class="pick color-pick ${x===selectedColor?'selected':''}" style="--c:${x}" data-v="${x}" aria-label="${x}"></button>`).join('');ip.querySelectorAll('.pick').forEach(b=>b.onclick=()=>{selectedIcon=b.dataset.v;setupPickers();updatePreview()});cp.querySelectorAll('.pick').forEach(b=>b.onclick=()=>{selectedColor=b.dataset.v;setupPickers();updatePreview()})}
function updatePreview(){const p=document.getElementById('tripPreview');p.style.setProperty('--trip-color',selectedColor);const name=document.getElementById('tripName').value||t('new_trip');p.innerHTML=selectedImage?`<img src="${selectedImage}" alt=""><div><small>${esc(document.getElementById('tripDestination').value||'')}</small><strong>${esc(name)}</strong></div>`:`<div class="preview-icon">${selectedIcon}</div><div><small>${esc(document.getElementById('tripDestination').value||'')}</small><strong>${esc(name)}</strong></div>`}
function openModal(id=null){editingId=id;selectedImage='';selectedIcon=icons[0];selectedColor=colors[0];document.getElementById('modalTitle').textContent=id?t('edit'):t('create_trip');const tr=trips.find(x=>x.id===id);if(tr){selectedImage=tr.image||'';selectedIcon=tr.icon||icons[0];selectedColor=tr.color||colors[0];for(const [id2,key] of [['tripName','name'],['tripDestination','destination'],['tripStart','start'],['tripEnd','end'],['tripTravelers','travelers'],['tripPhrase','phrase']])document.getElementById(id2).value=tr[key]||''}else document.getElementById('tripForm').reset();setupPickers();updatePreview();document.getElementById('tripModal').classList.remove('hidden');document.getElementById('tripModal').setAttribute('aria-hidden','false')}
function closeModal(){document.getElementById('tripModal').classList.add('hidden');document.getElementById('tripModal').setAttribute('aria-hidden','true')}
function submitTrip(e){e.preventDefault();const data={id:editingId||crypto.randomUUID(),name:document.getElementById('tripName').value.trim(),destination:document.getElementById('tripDestination').value.trim(),start:document.getElementById('tripStart').value,end:document.getElementById('tripEnd').value,travelers:document.getElementById('tripTravelers').value.trim(),phrase:document.getElementById('tripPhrase').value.trim(),icon:selectedIcon,color:selectedColor,image:selectedImage,createdAt:Date.now()};if(editingId){const i=trips.findIndex(x=>x.id===editingId);data.createdAt=trips[i].createdAt;trips[i]=data}else trips.unshift(data);save();closeModal();renderHome();openTrip(data.id)}
function removeTrip(id){if(!confirm(lang==='es'?'¿Eliminar este viaje? Esta acción no se puede deshacer.':t('delete')+'?'))return;trips=trips.filter(x=>x.id!==id);save();renderHome()}
function openTrip(id){currentId=id;document.getElementById('homeView').classList.remove('active');document.getElementById('tripView').classList.add('active');renderTrip(id);window.scrollTo({top:0,behavior:'smooth'})}
function renderTrip(id){const tr=trips.find(x=>x.id===id);if(!tr)return;const hero=document.getElementById('tripHero');hero.style.setProperty('--trip-color',tr.color);hero.innerHTML=`<div class="hero-image">${tr.image?`<img src="${tr.image}" alt="">`:`<div class="hero-symbol">${tr.icon}</div>`}</div><div class="hero-info"><div class="eyebrow">${esc(tr.destination||'')}</div><h1>${esc(tr.name)}</h1><p>${tr.start&&tr.end?`${formatDate(tr.start)} → ${formatDate(tr.end)} · ${daysBetween(tr.start,tr.end)} ${t('days')}`:t('no_dates')}</p><p class="phrase">${esc(tr.phrase||'')}</p></div><button id="tripEditBtn" class="hero-edit">✏️</button>`;document.getElementById('tripEditBtn').onclick=()=>openModal(id);renderTripTab('overview')}
function renderTripTab(tab){document.querySelectorAll('.trip-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const box=document.getElementById('tripContent');if(tab==='overview'){const tr=trips.find(x=>x.id===currentId);box.innerHTML=`<div class="stats"><div><b>${daysBetween(tr.start,tr.end)||'—'}</b><span>${t('days')}</span></div><div><b>${(tr.travelers||'').split(',').filter(Boolean).length||0}</b><span>${t('travelers')}</span></div><div><b>${tr.destination?esc(tr.destination):'—'}</b><span>${t('destination')}</span></div></div><div class="card welcome-card"><div class="big-emoji">${tr.icon}</div><h2>${esc(tr.phrase||tr.name)}</h2><p>${t('coming_soon')}</p></div>`}else box.innerHTML=`<div class="card"><h2>${tab==='itinerary'?'🗓️':tab==='reservations'?'🎟️':tab==='expenses'?'💰':'❤️'} ${t(tab)}</h2><p>${t('coming_soon')}</p><button class="primary" onclick="alert('${t('coming_soon').replace(/'/g,"\\'")}')">＋ ${t(tab==='itinerary'?'add_day':'new_trip')}</button></div>`}
document.getElementById('newTripBtn').onclick=()=>openModal();document.getElementById('emptyNewTrip').onclick=()=>openModal();document.getElementById('closeModal').onclick=closeModal;document.getElementById('backBtn').onclick=()=>{currentId=null;document.getElementById('tripView').classList.remove('active');document.getElementById('homeView').classList.add('active');renderHome()};document.getElementById('tripForm').onsubmit=submitTrip;document.getElementById('uploadImageBtn').onclick=()=>document.getElementById('tripImage').click();document.getElementById('tripImage').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2500000){alert('La imagen debe pesar menos de 2,5 MB.');e.target.value='';return}const r=new FileReader();r.onload=()=>{selectedImage=r.result;updatePreview()};r.readAsDataURL(f)};['tripName','tripDestination'].forEach(id=>document.getElementById(id).addEventListener('input',updatePreview));document.querySelectorAll('.trip-tab').forEach(b=>b.onclick=()=>renderTripTab(b.dataset.tab));document.getElementById('languageBtn').onclick=()=>{const list=['es','en','fr','de','it'];lang=list[(list.indexOf(lang)+1)%list.length];localStorage.setItem(LANG_KEY,lang);applyLang()};document.getElementById('tripModal').addEventListener('click',e=>{if(e.target.id==='tripModal')closeModal()});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.error));
applyLang();
